version: '3'
services:
    postgres-server:
        image: postgres:latest
        volumes:
            - ./postgres/lib/postgresql/data:/var/lib/postgresql/data:rw
        environment:
            - POSTGRES_USER=zabbix
            - POSTGRES_PASSWORD=zabbix
            - POSTGRES_DB=zabbix

    zabbix-server-psql:
        image: zabbix/zabbix-server-pgsql:ubuntu-4.4-latest
        restart: always
        environment:
            - DB_SERVER_HOST=postgres-server
            - POSTGRES_USER=zabbix
            - POSTGRES_PASSWORD=zabbix
            - POSTGRES_DB=zabbix
        links:
            - postgres-server:postgres-server
        depends_on:
            - postgres-server
        ports:
            - 11051:10051

    zabbix-web-psql:
        image: zabbix/zabbix-web-nginx-pgsql:ubuntu-4.4-latest
        restart: always
        environment:
            - DB_SERVER_HOST=postgres-server
            - POSTGRES_USER=zabbix
            - POSTGRES_PASSWORD=zabbix
            - POSTGRES_DB=zabbix
        links:
            - postgres-server:postgres-server
            - zabbix-server-psql:zabbix-server
        depends_on:
            - postgres-server
            - zabbix-server-psql
        ports:
            - 9080:8080
            - 9443:8443

    mysql-server:

        image: percona
        restart: always
        user: "999:999"
        environment:
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=zabbix_pwd
            - MYSQL_ROOT_PASSWORD=root_pwd
        volumes:
            - ./percona/lib/mysql:/var/lib/mysql:rw
        command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]

    zabbix-server-mysql:
        image: zabbix/zabbix-server-mysql:ubuntu-4.4-latest
        restart: always
        environment:
            - DB_SERVER_HOST=mysql-server
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=zabbix_pwd
            - MYSQL_ROOT_PASSWORD=root_pwd
            - ZBX_CACHESIZE=64M
        links:
            - mysql-server:mysql-server
        ports:
            - 10051:10051
        depends_on:
            - mysql-server

    zabbix-web-mysql:
        image: zabbix/zabbix-web-nginx-mysql:ubuntu-4.4-latest
        restart: always
        environment:
            - DB_SERVER_HOST=mysql-server
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=zabbix_pwd
            - MYSQL_ROOT_PASSWORD=root_pwd
            - ZBX_MEMORYLIMIT=256M
            - ZBX_UPLOADMAXFILESIZE=4M
        links:
            - mysql-server:mysql-server
            - zabbix-server-mysql:zabbix-server
        depends_on:
            - mysql-server
            - zabbix-server-mysql
        ports:
            - 8080:8080
            - 8443:8443
